backend:
  name: github
  repo: taxa6953/test-site
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "صفحات"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "محتوا", name: "body", widget: "markdown" }
